In [130]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob

In [131]:
df = pd.read_csv("states3.csv")
df

,Unnamed: 0,State,TotalPop,Hispanic,White,Black,Native,Asian,Pacific,Income,GenderPop
0,0,Iowa,3093526,5.30%,87.72%,3.26%,0.29%,1.70%,0.06%,"$53,017.75",1534595M_1558931F
1,1,Kansas,2892987,11.64%,75.96%,6.57%,0.73%,2.33%,NaN,"$53,885.61",1439862M_1453125F
2,2,Kentucky,4397353,3.22%,85.23%,8.27%,0.17%,1.13%,0.05%,"$45,285.80",2164208M_2233145F
3,3,Louisiana,4625253,4.87%,54.98%,36.33%,0.48%,1.67%,0.04%,"$44,957.99",2261156M_2364097F
4,4,Maine,1329100,1.43%,93.71%,1.13%,0.79%,0.97%,0.02%,"$49,181.97",650081M_679019F
5,5,Maryland,5930538,8.47%,52.68%,30.68%,0.20%,5.33%,0.04%,"$78,765.40",2872643M_F

In [132]:
files = glob.glob("states*.csv")
states_list = []
for filename in files:
    data = pd.read_csv(filename)
    states_list.append(data)

us_census = pd.concat(states_list)

In [133]:
us_census.columns

Index(['Unnamed: 0', 'State', 'TotalPop', 'Hispanic', 'White', 'Black',
       'Native', 'Asian', 'Pacific', 'Income', 'GenderPop'],
      dtype='object')

In [134]:
us_census.dtypes

Unnamed: 0     int64
State         object
TotalPop       int64
Hispanic      object
White         object
Black         object
Native        object
Asian         object
Pacific       object
Income        object
GenderPop     object
dtype: object

In [135]:
us_census

,Unnamed: 0,State,TotalPop,Hispanic,White,Black,Native,Asian,Pacific,Income,GenderPop
0,0,Rhode Island,1053661,13.36%,74.33%,5.68%,0.35%,3.25%,0.04%,"$59,125.27",510388M_543273F
1,1,South Carolina,4777576,5.06%,62.89%,28.75%,0.29%,1.25%,0.05%,"$46,296.81",2322409M_2455167F
2,2,South Dakota,843190,3.24%,82.50%,1.42%,9.42%,1.02%,0.04%,"$51,805.41",423477M_419713F
3,3,Tennessee,6499615,4.72%,73.49%,18.28%,0.23%,1.41%,0.04%,"$47,328.08",3167756M_3331859F
4,4,Texas,26538614,38.05%,44.69%,11.65%,0.26%,3.67%,0.07%,"$55,874.52",13171316M_13367298F
5,5,Utah,2903379,13.47%,79.41%,1.02%,1.08%,2.20%,0.83%,"$63,488.92",1459229M_1444150F
0,0,Utah,2903379,13.47%,79.41%,1.02%,1.08%,2.20%,0.83%,"$63,488.92",1459229M_1444150F
1,1,Vermont,626604,1.61%,93.98%,0.98%,0.30%,1.24%,0.03%,"$55,602.97",308573M_318031F
2,2,Virginia,8256630,8.01%,63.27%,20.18%,0.21%,5.46%,0.06%,"$72,866.01",4060948M_4195682F
3,3,Washington,6985464,11.14%,72.04%,3.38%,1.41%,7.02%,0.61%,"$64,493.77",3487725M_3497739F
4,4,West Virginia,1851420,1.29%,92.18%,3.66%,0.15%,0.68%,0.03%,"$41,437.11",913631M_937789F
5,5,Wisconsin,5742117,6.68%,79.86%,8.20%,0.95%,2.40%,0.02%,"$53,898.89",2851385M_2890732F
0,0,Maryland,5930538,8.47%,52.68%,30.68%,0.20%,5.33%,0.04%,"$78,765.40",2872643M_F
1,1,Massachusetts,6705586,11.46%,73.04%,6.83%,0.13%,5.84%,0.02%,"$72,838.94",3249650M_3455936F
2,2,Michigan,9900571,4.63%,72.38%,17.63%,0.48%,2.42%,0.02%,"$51,201.83",4861973M_5038598F
3,3,Minnesota,5419171,5.15%,81.43%,5.66%,1.07%,4.16%,0.03%,"$62,820.83",2692166M_2727005F
4,4,Mississippi,2988081,2.84%,53.29%,41.49%,0.39%,0.88%,0.02%,"$38,909.92",1451723M_1536358F
5,5,Missouri,6045448,4.04%,77.51%,14.12%,0.36%,1.62%,0.10%,"$49,763.99",2964003M_3081445F
0,0,Missouri,6045448,4.04%,77.51%,14.12%,0.36%,1.62%,0.10%,"$49,763.99",2964003M_3081445F
1,1,Montana,1014699,3.27%,86.42%,0.43%,7.06%,0.57%,0.07%,"$47,645.68",510163M_F
2,2,Nebraska,1869365,9.20%,81.14%,4.96%,0.86%,1.86%,0.06%,"$55,916.47",929606M_939759F
3,3,Nevada,2798636,27.10%,53.24%,7.74%,1.09%,7.10%,0.57%,"$55,526.53",1407735M_1390901F
4,4,New Hampshire,1324201,3.32%,91.32%,1.23%,0.14%,2.19%,0.02%,"$68,728.86",653484M_670717F
5,5,New Jersey,8904413,18.75%,56.49%,14.39%,0.12%,8.16%,0.03%,"$76,581.08",4343027M_4561386F
0,0,Ohio,11575977,3.67%,75.90%,16.21%,0.17%,1.62%,0.02%,"$49,655.25",5662893M_5913084F
1,1,Oklahoma,3849733,10.08%,66.06%,8.31%,6.72%,1.80%,0.11%,"$48,100.85",1906944M_1942789F
2,2,Oregon,3939233,11.44%,78.40%,1.73%,1.00%,3.59%,0.35%,"$54,271.90",1948453M_1990780F
3,3,Pennsylvania,12779559,6.13%,77.38%,11.63%,0.12%,2.80%,0.02%,"$56,170.46",6245344M_6534215F
4,4,Puerto Rico,3583073,98.89%,0.77%,0.09%,0.00%,0.08%,0.00%,"$20,720.54",1713860M_1869213F
5,5,Rhode Island,1053661,13.36%,74.33%,5.68%,0.35%,3.25%,0.04%,"$59,125.27",510388M_543273F
0,0,New Jersey,8904413,18.75%,56.49%,14.39%,0.12%,8.16%,0.03%,"$76,581.08",4343027M_4561386F
1,1,New Mexico,2084117,45.28%,40.70%,1.76%,9.25%,1.23%,0.04%,"$47,329.97",1032414M_1051703F
2,2,New York,19673174,17.24%,56.47%,15.67%,0.32%,7.90%,0.02%,"$64,290.75",9541801M_10131373F
3,3,North Carolina,9845333,8.46%,64.60%,21.40%,1.09%,2.32%,0.05%,"$49,937.46",4795408M_5049925F
4,4,North Dakota,721640,2.83%,87.45%,1.28%,5.65%,0.96%,NaN,"$58,188.11",367963M_353677F
5,5,Ohio,11575977,3.67%,75.90%,16.21%,0.17%,1.62%,0.02%,"$49,655.25",5662893M_5913084F
0,0,Georgia,10006693,8.42%,54.29%,32.09%,0.19%,3.10%,0.05%,"$50,811.08",4883331M_5123362F
1,1,Hawaii,1406299,9.19%,25.03%,2.05%,0.14%,36.59%,8.76%,"$73,264.43",709871M_696428F
2,2,Idaho,1616547,11.51%,83.14%,0.57%,1.47%,1.14%,0.13%,"$48,017.32",810464M_806083F
3,3,Illinois,12873761,15.60%,60.86%,17.11%,0.12%,4.48%,0.02%,"$59,587.05",6316899M_6556862F
4,4,Indiana,6568645,6.54%,78.43%,11.19%,0.19%,1.58%,0.03%,"$48,616.23",3235263M_3333382F
5,5,Iowa,3093526,5.30%,87.72%,3.26%,0.29%,1.70%,0.06%,"$53,017.75",1534595M_1558931F
0,0,Iowa,3093526,5.30%,87.72%,3.26%,0.29%,1.70%,0.06%,"$53,017.75",1534595M_1558931F
1,1,Kansas,2892987,11.64%,75.96%,6.57%,0.73%,2.33%,NaN,"$53,885.61",1439862M_1453125F
2,2,Kentucky,4397353,3.22%,85.23%,8.27%,0.17%,1.13%,0.05%,"$45,285.80",2164208M_2233145F
3,3,Louisiana,4625253,4.87%,54.98%,36.33%,0.48%,1.67%,0.04%,"$44,957.99",2261156M_2364097F
4,4,Maine,1329100,1.43%,93.71%,1.13%,0.79%,0.97%,0.02%,"$49,181.97",650081M_679019F
5,5,Maryland,5930538,8.47%,52.68%,30.68%,0.20%,5.33%,0.04%,"$78,765.40",2872643M_F
0,0,Colorado,5278906,20.78%,69.90%,3.55%,0.57%,2.66%,NaN,"$64,657.80",2648667M_2630239F
1,1,Connecticut,3593222,15.60%,67.68%,10.35%,0.13%,4.02%,0.02%,"$76,146.56",1751607M_1841615F
2,2,Delaware,926454,8.82%,64.63%,20.74%,0.26%,3.27%,NaN,"$61,827.98",448413M_478041F
3,3,District of Columbia,647484,9.17%,33.10%,51.78%,0.20%,3.38%,0.03%,"$75,466.36",306674M_340810F
4,4,Florida,19645772,21.34%,59.08%,15.17%,0.21%,2.28%,0.05%,"$50,690.19",9600009M_10045763F
5,5,Georgia,10006693,8.42%,54.29%,32.09%,0.19%,3.10%,0.05%,"$50,811.08",4883331M_5123362F
0,0,Alabama,4830620,3.75%,61.88%,31.25%,0.45%,1.05%,0.03%,"$43,296.36",2341093M_2489527F
1,1,Alaska,733375,5.91%,60.91%,2.85%,16.39%,5.45%,1.06%,"$70,354.74",384160M_349215F
2,2,Arizona,6641928,29.57%,57.12%,3.85%,4.36%,2.88%,0.17%,"$54,207.82",3299088M_3342840F
3,3,Arkansas,2958208,6.22%,71.14%,18.97%,0.52%,1.14%,0.15%,"$41,935.63",1451913M_1506295F
4,4,California,38421464,37.29%,40.22%,5.68%,0.41%,13.05%,0.35%,"$67,264.78",19087135M_19334329F
5,5,Colorado,5278906,20.78%,69.90%,3.55%,0.57%,2.66%,NaN,"$64,657.80",2648667M_2630239F

## Recovering data

In [136]:
us_census["Income"] = (us_census["Income"].replace('[\$,]', '', regex=True))
us_census["Income"] = (us_census["Income"].replace('[\,]', '', regex=True))


us_census["Income"] = pd.to_numeric(us_census["Income"])

us_census["Income"]

0    59125.27
1    46296.81
2    51805.41
3    47328.08
4    55874.52
5    63488.92
0    63488.92
1    55602.97
2    72866.01
3    64493.77
4    41437.11
5    53898.89
0    78765.40
1    72838.94
2    51201.83
3    62820.83
4    38909.92
5    49763.99
0    49763.99
1    47645.68
2    55916.47
3    55526.53
4    68728.86
5    76581.08
0    49655.25
1    48100.85
2    54271.90
3    56170.46
4    20720.54
5    59125.27
0    76581.08
1    47329.97
2    64290.75
3    49937.46
4    58188.11
5    49655.25
0    50811.08
1    73264.43
2    48017.32
3    59587.05
4    48616.23
5    53017.75
0    53017.75
1    53885.61
2    45285.80
3    44957.99
4    49181.97
5    78765.40
0    64657.80
1    76146.56
2    61827.98
3    75466.36
4    50690.19
5    50811.08
0    43296.36
1    70354.74
2    54207.82
3    41935.63
4    67264.78
5    64657.80
Name: Income, dtype: float64

In [137]:
us_census["GenderPop"].head()

us_census[["Men Count", "Women Count"]] = us_census["GenderPop"].str.split("_", expand=True)

us_census["Men Count"] = pd.to_numeric(us_census["Men Count"].str.replace("M", "", regex=False))
us_census["Women Count"] = pd.to_numeric(us_census["Women Count"].str.replace("F", "", regex=False))

us_census['Women Count'] = us_census['Women Count'].fillna(us_census['TotalPop'] - us_census['Men Count']).astype(int)

In [138]:
us_census.dtypes

Unnamed: 0       int64
State           object
TotalPop         int64
Hispanic        object
White           object
Black           object
Native          object
Asian           object
Pacific         object
Income         float64
GenderPop       object
Men Count        int64
Women Count      int64
dtype: object

In [139]:
us_census["Women Count"].isna().sum()

np.int64(0)

In [140]:
us_census["Men Count"].isna().sum()

np.int64(0)

In [141]:
us_census.dtypes

Unnamed: 0       int64
State           object
TotalPop         int64
Hispanic        object
White           object
Black           object
Native          object
Asian           object
Pacific         object
Income         float64
GenderPop       object
Men Count        int64
Women Count      int64
dtype: object

In [143]:
us_census["Women Count"]

0      543273
1     2455167
2      419713
3     3331859
4    13367298
5     1444150
0     1444150
1      318031
2     4195682
3     3497739
4      937789
5     2890732
0     3057895
1     3455936
2     5038598
3     2727005
4     1536358
5     3081445
0     3081445
1      504536
2      939759
3     1390901
4      670717
5     4561386
0     5913084
1     1942789
2     1990780
3     6534215
4     1869213
5      543273
0     4561386
1     1051703
2    10131373
3     5049925
4      353677
5     5913084
0     5123362
1      696428
2      806083
3     6556862
4     3333382
5     1558931
0     1558931
1     1453125
2     2233145
3     2364097
4      679019
5     3057895
0     2630239
1     1841615
2      478041
3      340810
4    10045763
5     5123362
0     2489527
1      349215
2     3342840
3     1506295
4    19334329
5     2630239
Name: Women Count, dtype: int64

In [144]:
us_census

,Unnamed: 0,State,TotalPop,Hispanic,White,Black,Native,Asian,Pacific,Income,GenderPop,Men Count,Women Count
0,0,Rhode Island,1053661,13.36%,74.33%,5.68%,0.35%,3.25%,0.04%,59125.27,510388M_543273F,510388,543273
1,1,South Carolina,4777576,5.06%,62.89%,28.75%,0.29%,1.25%,0.05%,46296.81,2322409M_2455167F,2322409,2455167
2,2,South Dakota,843190,3.24%,82.50%,1.42%,9.42%,1.02%,0.04%,51805.41,423477M_419713F,423477,419713
3,3,Tennessee,6499615,4.72%,73.49%,18.28%,0.23%,1.41%,0.04%,47328.08,3167756M_3331859F,3167756,3331859
4,4,Texas,26538614,38.05%,44.69%,11.65%,0.26%,3.67%,0.07%,55874.52,13171316M_13367298F,13171316,13367298
5,5,Utah,2903379,13.47%,79.41%,1.02%,1.08%,2.20%,0.83%,63488.92,1459229M_1444150F,1459229,1444150
0,0,Utah,2903379,13.47%,79.41%,1.02%,1.08%,2.20%,0.83%,63488.92,1459229M_1444150F,1459229,1444150
1,1,Vermont,626604,1.61%,93.98%,0.98%,0.30%,1.24%,0.03%,55602.97,308573M_318031F,308573,318031
2,2,Virginia,8256630,8.01%,63.27%,20.18%,0.21%,5.46%,0.06%,72866.01,4060948M_4195682F,4060948,4195682
3,3,Washington,6985464,11.14%,72.04%,3.38%,1.41%,7.02%,0.61%,64493.77,3487725M_3497739F,3487725,3497739
4,4,West Virginia,1851420,1.29%,92.18%,3.66%,0.15%,0.68%,0.03%,41437.11,913631M_937789F,913631,937789
5,5,Wisconsin,5742117,6.68%,79.86%,8.20%,0.95%,2.40%,0.02%,53898.89,2851385M_2890732F,2851385,2890732
0,0,Maryland,5930538,8.47%,52.68%,30.68%,0.20%,5.33%,0.04%,78765.40,2872643M_F,2872643,3057895
1,1,Massachusetts,6705586,11.46%,73.04%,6.83%,0.13%,5.84%,0.02%,72838.94,3249650M_3455936F,3249650,3455936
2,2,Michigan,9900571,4.63%,72.38%,17.63%,0.48%,2.42%,0.02%,51201.83,4861973M_5038598F,4861973,5038598
3,3,Minnesota,5419171,5.15%,81.43%,5.66%,1.07%,4.16%,0.03%,62820.83,2692166M_2727005F,2692166,2727005
4,4,Mississippi,2988081,2.84%,53.29%,41.49%,0.39%,0.88%,0.02%,38909.92,1451723M_1536358F,1451723,1536358
5,5,Missouri,6045448,4.04%,77.51%,14.12%,0.36%,1.62%,0.10%,49763.99,2964003M_3081445F,2964003,3081445
0,0,Missouri,6045448,4.04%,77.51%,14.12%,0.36%,1.62%,0.10%,49763.99,2964003M_3081445F,2964003,3081445
1,1,Montana,1014699,3.27%,86.42%,0.43%,7.06%,0.57%,0.07%,47645.68,510163M_F,510163,504536
2,2,Nebraska,1869365,9.20%,81.14%,4.96%,0.86%,1.86%,0.06%,55916.47,929606M_939759F,929606,939759
3,3,Nevada,2798636,27.10%,53.24%,7.74%,1.09%,7.10%,0.57%,55526.53,1407735M_1390901F,1407735,1390901
4,4,New Hampshire,1324201,3.32%,91.32%,1.23%,0.14%,2.19%,0.02%,68728.86,653484M_670717F,653484,670717
5,5,New Jersey,8904413,18.75%,56.49%,14.39%,0.12%,8.16%,0.03%,76581.08,4343027M_4561386F,4343027,4561386
0,0,Ohio,11575977,3.67%,75.90%,16.21%,0.17%,1.62%,0.02%,49655.25,5662893M_5913084F,5662893,5913084
1,1,Oklahoma,3849733,10.08%,66.06%,8.31%,6.72%,1.80%,0.11%,48100.85,1906944M_1942789F,1906944,1942789
2,2,Oregon,3939233,11.44%,78.40%,1.73%,1.00%,3.59%,0.35%,54271.90,1948453M_1990780F,1948453,1990780
3,3,Pennsylvania,12779559,6.13%,77.38%,11.63%,0.12%,2.80%,0.02%,56170.46,6245344M_6534215F,6245344,6534215
4,4,Puerto Rico,3583073,98.89%,0.77%,0.09%,0.00%,0.08%,0.00%,20720.54,1713860M_1869213F,1713860,1869213
5,5,Rhode Island,1053661,13.36%,74.33%,5.68%,0.35%,3.25%,0.04%,59125.27,510388M_543273F,510388,543273
0,0,New Jersey,8904413,18.75%,56.49%,14.39%,0.12%,8.16%,0.03%,76581.08,4343027M_4561386F,4343027,4561386
1,1,New Mexico,2084117,45.28%,40.70%,1.76%,9.25%,1.23%,0.04%,47329.97,1032414M_1051703F,1032414,1051703
2,2,New York,19673174,17.24%,56.47%,15.67%,0.32%,7.90%,0.02%,64290.75,9541801M_10131373F,9541801,10131373
3,3,North Carolina,9845333,8.46%,64.60%,21.40%,1.09%,2.32%,0.05%,49937.46,4795408M_5049925F,4795408,5049925
4,4,North Dakota,721640,2.83%,87.45%,1.28%,5.65%,0.96%,NaN,58188.11,367963M_353677F,367963,353677
5,5,Ohio,11575977,3.67%,75.90%,16.21%,0.17%,1.62%,0.02%,49655.25,5662893M_5913084F,5662893,5913084
0,0,Georgia,10006693,8.42%,54.29%,32.09%,0.19%,3.10%,0.05%,50811.08,4883331M_5123362F,4883331,5123362
1,1,Hawaii,1406299,9.19%,25.03%,2.05%,0.14%,36.59%,8.76%,73264.43,709871M_696428F,709871,696428
2,2,Idaho,1616547,11.51%,83.14%,0.57%,1.47%,1.14%,0.13%,48017.32,810464M_806083F,810464,806083
3,3,Illinois,12873761,15.60%,60.86%,17.11%,0.12%,4.48%,0.02%,59587.05,6316899M_6556862F,6316899,6556862
4,4,Indiana,6568645,6.54%,78.43%,11.19%,0.19%,1.58%,0.03%,48616.23,3235263M_3333382F,3235263,3333382
5,5,Iowa,3093526,5.30%,87.72%,3.26%,0.29%,1.70%,0.06%,53017.75,1534595M_1558931F,1534595,1558931
0,0,Iowa,3093526,5.30%,87.72%,3.26%,0.29%,1.70%,0.06%,53017.75,1534595M_1558931F,1534595,1558931
1,1,Kansas,2892987,11.64%,75.96%,6.57%,0.73%,2.33%,NaN,53885.61,1439862M_1453125F,1439862,1453125
2,2,Kentucky,4397353,3.22%,85.23%,8.27%,0.17%,1.13%,0.05%,45285.80,2164208M_2233145F,2164208,2233145
3,3,Louisiana,4625253,4.87%,54.98%,36.33%,0.48%,1.67%,0.04%,44957.99,2261156M_2364097F,2261156,2364097
4,4,Maine,1329100,1.43%,93.71%,1.13%,0.79%,0.97%,0.02%,49181.97,650081M_679019F,650081,679019
5,5,Maryland,5930538,8.47%,52.68%,30.68%,0.20%,5.33%,0.04%,78765.40,2872643M_F,2872643,3057895
0,0,Colorado,5278906,20.78%,69.90%,3.55%,0.57%,2.66%,NaN,64657.80,2648667M_2630239F,2648667,2630239
1,1,Connecticut,3593222,15.60%,67.68%,10.35%,0.13%,4.02%,0.02%,76146.56,1751607M_1841615F,1751607,1841615
2,2,Delaware,926454,8.82%,64.63%,20.74%,0.26%,3.27%,NaN,61827.98,448413M_478041F,448413,478041
3,3,District of Columbia,647484,9.17%,33.10%,51.78%,0.20%,3.38%,0.03%,75466.36,306674M_340810F,306674,340810
4,4,Florida,19645772,21.34%,59.08%,15.17%,0.21%,2.28%,0.05%,50690.19,9600009M_10045763F,9600009,10045763
5,5,Georgia,10006693,8.42%,54.29%,32.09%,0.19%,3.10%,0.05%,50811.08,4883331M_5123362F,4883331,5123362
0,0,Alabama,4830620,3.75%,61.88%,31.25%,0.45%,1.05%,0.03%,43296.36,2341093M_2489527F,2341093,2489527
1,1,Alaska,733375,5.91%,60.91%,2.85%,16.39%,5.45%,1.06%,70354.74,384160M_349215F,384160,349215
2,2,Arizona,6641928,29.57%,57.12%,3.85%,4.36%,2.88%,0.17%,54207.82,3299088M_3342840F,3299088,3342840
3,3,Arkansas,2958208,6.22%,71.14%,18.97%,0.52%,1.14%,0.15%,41935.63,1451913M_1506295F,1451913,1506295
4,4,California,38421464,37.29%,40.22%,5.68%,0.41%,13.05%,0.35%,67264.78,19087135M_19334329F,19087135,19334329
5,5,Colorado,5278906,20.78%,69.90%,3.55%,0.57%,2.66%,NaN,64657.80,2648667M_2630239F,2648667,2630239